/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador.IU;

import gerenciador.Controlador.Controlador;
import gerenciador.principal.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas Bernardo
 */
public class IUCadastroTecnico extends javax.swing.JDialog {

    /**
     * Creates new form IUCadastroTecnico
     */
    public IUCadastroTecnico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        msgLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigo_Text = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome_Text = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        salario_Text = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        salvar_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        nomeDep_Text = new javax.swing.JTextField();
        msgLabel = new javax.swing.JLabel();
        nivelCombo = new javax.swing.JComboBox<>();
        funcaoCombo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Técnico");

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel3.setText("Salário");

        jLabel4.setText("Nível");

        jLabel5.setText("Função");

        salvar_Button.setText("Salvar");
        salvar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome do Departamento");

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLabel.setText("Mensagem");

        nivelCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "T1", "T2" }));
        nivelCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelComboActionPerformed(evt);
            }
        });

        funcaoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acessor", "Laboratório", "Secretário" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(codigo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nivelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2)
                                    .addComponent(nome_Text, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(funcaoCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(salario_Text, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(4, 4, 4))
                            .addComponent(nomeDep_Text))))
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(salvar_Button)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nome_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(salario_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nivelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(funcaoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(7, 7, 7)
                .addComponent(nomeDep_Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar_Button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(msgLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_ButtonActionPerformed
        // TODO add your handling code here:
        String codigo = codigo_Text.getText();
        String nome = nome_Text.getText();
        double salario = Double.parseDouble(salario_Text.getText());
        String nivel = (String) nivelCombo.getSelectedItem();
        String funcao = (String) funcaoCombo.getSelectedItem();
        String nomeDep = nomeDep_Text.getText();
        Controlador control = new Controlador();
        if(control.espacoLivreDep(nomeDep)){
            salvar_Button.setEnabled(false);
            Funcionario f = control.buscaFuncionarioCod(codigo, nomeDep); //Verificando se funcionario já existe
            if(f == null){ //Se não existir eu salvo o funcionario
                salvar_Button.setEnabled(true);
                control.addTecnico(codigo, nome, salario, nivel, funcao, nomeDep);
                //msgLabel.setVisible(true);
                //msgLabel.setText("Técnico adicionado com sucesso!");
                JOptionPane.showMessageDialog(null, "Técnico adicionado com sucesso!");
                salvar_Button.setEnabled(false);
            }
            else{
                //msgLabel.setVisible(true);
                //msgLabel.setText("Técnico já existe em nosso banco de dados!");
                JOptionPane.showMessageDialog(null, "Técnico já existe em nosso banco de dados!");
                salvar_Button.setEnabled(false);
            }
        }
        else{
            //msgLabel.setVisible(true);
            //msgLabel.setText("Técnico não adicionado limite de funcionários no departamento atingido!");
            JOptionPane.showMessageDialog(null, "Técnico não adicionado limite de funcionários no departamento atingido!");
            salvar_Button.setEnabled(false);
        }
        
    }//GEN-LAST:event_salvar_ButtonActionPerformed

    private void nivelComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nivelComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUCadastroTecnico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUCadastroTecnico dialog = new IUCadastroTecnico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigo_Text;
    private javax.swing.JComboBox<String> funcaoCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JComboBox<String> nivelCombo;
    private javax.swing.JTextField nomeDep_Text;
    private javax.swing.JTextField nome_Text;
    private javax.swing.JTextField salario_Text;
    private javax.swing.JButton salvar_Button;
    // End of variables declaration//GEN-END:variables
}
