/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador.IU;

import gerenciador.Controlador.Controlador;
import gerenciador.principal.Departamento;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucas Bernardo
 */
public class IUInformacoesDep extends javax.swing.JDialog {

    private DefaultListModel modeloList = new DefaultListModel();
    private DefaultListModel modelList = new DefaultListModel();

    /**
     * Creates new form IUInformacoesDep
     */
    public IUInformacoesDep(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        departamentosList.setModel(modeloList);
        Controlador control = new Controlador();
        String nomesDep[] = control.nomesDepartamentos();
        for (int i = 0; i < nomesDep.length; i++) {
            modeloList.addElement(nomesDep[i]);
        }
        gastosLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        codigoText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        departamentosList = new javax.swing.JList<>();
        buscarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoList = new javax.swing.JList<>();
        gastosLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jScrollPane1.setViewportView(departamentosList);

        buscarButton.setText("Buscar");
        buscarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarButtonActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(infoList);

        gastosLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        gastosLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gastosLabel.setText("Gastos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buscarButton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(gastosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 4, Short.MAX_VALUE)
                        .addComponent(buscarButton))
                    .addComponent(gastosLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarButtonActionPerformed
        // TODO add your handling code here:
        infoList.setModel(modelList);
        modelList.removeAllElements();
        int indice = departamentosList.getSelectedIndex();
        String nomeDep = (String) modeloList.getElementAt(indice);
        String codDep = codigoText.getText();
        Controlador control = new Controlador();
        if (indice >= 0) {
            Departamento d = control.buscaDepNome(nomeDep);
            if (d == null) {
                JOptionPane.showMessageDialog(null, "Departamento não existe em nosso banco de dados!");
            } else {
                String fun[] = control.nomesFuncionarios(nomeDep);
                if (fun != null) {
                    for (int i = 0; i < fun.length; i++) {
                        modelList.addElement(fun[i]);
                    }
                    double gastos = control.gastosTotalDep(nomeDep);
                    gastosLabel.setVisible(true);
                    gastosLabel.setText("Gastos: " + gastos);
                }
                else{
                    JOptionPane.showMessageDialog(null, "Não há funcionários no fepartamento!");
                }
            }
        } else if (codDep != null) {
            Departamento d = control.buscaDepCod(codDep);
            if (d == null) {
                JOptionPane.showMessageDialog(null, "Departamento não existe em nosso banco de dados!");
            } else {
                //infoList.setModel(modelList);
                String nomeDepa = d.getNome();
                String fun[] = control.nomesFuncionarios(nomeDepa);
                if (fun != null) {
                    for (int i = 0; i < fun.length; i++) {
                        modelList.addElement(fun[i]);
                    }
                    double gastos = control.gastosTotalDep(nomeDepa);
                    gastosLabel.setVisible(true);
                    gastosLabel.setText("Gastos: " + gastos);
                } else {
                    JOptionPane.showMessageDialog(null, "Não há funcionários no fepartamento!");
                }
            }
        }
    }//GEN-LAST:event_buscarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUInformacoesDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUInformacoesDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUInformacoesDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUInformacoesDep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IUInformacoesDep dialog = new IUInformacoesDep(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarButton;
    private javax.swing.JTextField codigoText;
    private javax.swing.JList<String> departamentosList;
    private javax.swing.JLabel gastosLabel;
    private javax.swing.JList<String> infoList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
