/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gerenciador.IU;

import gerenciador.Controlador.Controlador;
import java.util.ArrayList;

/**
 *
 * @author Lucas Bernardo
 */
public class IUPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form IUPrincipal
     */
    public IUPrincipal() {
        initComponents();
        msgLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicializaUniMenu = new javax.swing.JMenu();
        inicializaUniItemMenu = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        criaDepartamentoMenu = new javax.swing.JMenuItem();
        addTecnicoMenu = new javax.swing.JMenuItem();
        addEfetivoMenu = new javax.swing.JMenuItem();
        addSubMenu = new javax.swing.JMenuItem();
        relatorioGeralMenuItem = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        buscaFuncCodMenu = new javax.swing.JMenuItem();
        buscaFunNomeMenu = new javax.swing.JMenuItem();
        filtrarFunSalarioMenuItem = new javax.swing.JMenuItem();
        filtrarDepGastosMenuItem = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        resumoDepsMenuItem = new javax.swing.JMenuItem();
        infoDepMenuItem = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Gerenciamento Universitário");

        msgLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msgLabel.setText("Mensagem");

        inicializaUniMenu.setText("Inicializar");

        inicializaUniItemMenu.setText("Inicializar Universidade");
        inicializaUniItemMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicializaUniItemMenuActionPerformed(evt);
            }
        });
        inicializaUniMenu.add(inicializaUniItemMenu);

        jMenuBar1.add(inicializaUniMenu);

        jMenu1.setText("Cadastro");

        criaDepartamentoMenu.setText("Criar novo departamento");
        criaDepartamentoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criaDepartamentoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(criaDepartamentoMenu);

        addTecnicoMenu.setText("Adicionar Técnico");
        addTecnicoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTecnicoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addTecnicoMenu);

        addEfetivoMenu.setText("Adicionar Docente Efetivo");
        addEfetivoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEfetivoMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addEfetivoMenu);

        addSubMenu.setText("Adicionar Docente Substituto");
        addSubMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSubMenuActionPerformed(evt);
            }
        });
        jMenu1.add(addSubMenu);

        jMenuBar1.add(jMenu1);

        relatorioGeralMenuItem.setText("Relatórios");
        relatorioGeralMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioGeralMenuItemActionPerformed(evt);
            }
        });

        jMenu3.setText("Buscar");

        buscaFuncCodMenu.setText("Funcionário por cód.");
        buscaFuncCodMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaFuncCodMenuActionPerformed(evt);
            }
        });
        jMenu3.add(buscaFuncCodMenu);

        buscaFunNomeMenu.setText("Funcionário por nome");
        buscaFunNomeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaFunNomeMenuActionPerformed(evt);
            }
        });
        jMenu3.add(buscaFunNomeMenu);

        filtrarFunSalarioMenuItem.setText("Filtrar Funcionários pelo Salário");
        filtrarFunSalarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarFunSalarioMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(filtrarFunSalarioMenuItem);

        filtrarDepGastosMenuItem.setText("Filtrar Departamentos por gastos");
        filtrarDepGastosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarDepGastosMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(filtrarDepGastosMenuItem);

        relatorioGeralMenuItem.add(jMenu3);

        jMenu4.setText("Exibir");

        jMenuItem1.setText("Funcionários");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuItem2.setText("Técnicos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuItem3.setText("Docentes");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Docentes Efetivos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuItem5.setText("Docentes Substitutos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        resumoDepsMenuItem.setText("Resumo dos Departamentos");
        resumoDepsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumoDepsMenuItemActionPerformed(evt);
            }
        });
        jMenu4.add(resumoDepsMenuItem);

        relatorioGeralMenuItem.add(jMenu4);

        infoDepMenuItem.setText("Info departamento");
        infoDepMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoDepMenuItemActionPerformed(evt);
            }
        });
        relatorioGeralMenuItem.add(infoDepMenuItem);

        jMenuItem6.setText("Geral");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        relatorioGeralMenuItem.add(jMenuItem6);

        jMenuBar1.add(relatorioGeralMenuItem);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(msgLabel)
                .addGap(88, 88, 88))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addEfetivoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEfetivoMenuActionPerformed
        // TODO add your handling code here:
        IUCadastroDocenteEfetivo IUCad = new IUCadastroDocenteEfetivo(this, true);
        IUCad.setLocationRelativeTo(this);
        IUCad.setVisible(true);
    }//GEN-LAST:event_addEfetivoMenuActionPerformed

    private void criaDepartamentoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criaDepartamentoMenuActionPerformed
        // TODO add your handling code here:
        Controlador control = new Controlador();
        if (control.getInstanciada()) {
            IUCadastroDepartamento IUCad = new IUCadastroDepartamento(this, true);
            IUCad.setLocationRelativeTo(this);
            IUCad.setVisible(true);
        } else {
            msgLabel.setVisible(true);
            msgLabel.setText("Universidade ainda não foi inicializada!");
        }
    }//GEN-LAST:event_criaDepartamentoMenuActionPerformed

    private void addTecnicoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTecnicoMenuActionPerformed
        // TODO add your handling code here:
        IUCadastroTecnico IUCad = new IUCadastroTecnico(this, true);
        IUCad.setLocationRelativeTo(this);
        IUCad.setVisible(true);
    }//GEN-LAST:event_addTecnicoMenuActionPerformed

    private void addSubMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSubMenuActionPerformed
        // TODO add your handling code here:
        IUCadastroDocenteSubstituto IUCad = new IUCadastroDocenteSubstituto(this, true);
        IUCad.setLocationRelativeTo(this);
        IUCad.setVisible(true);
    }//GEN-LAST:event_addSubMenuActionPerformed

    private void inicializaUniItemMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicializaUniItemMenuActionPerformed
        // TODO add your handling code here:
        IUCadastroUniversidade IUIni = new IUCadastroUniversidade(this, true);
        IUIni.setLocationRelativeTo(this);
        IUIni.setVisible(true);
    }//GEN-LAST:event_inicializaUniItemMenuActionPerformed

    private void buscaFunNomeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaFunNomeMenuActionPerformed
        // TODO add your handling code here:
        IUExibeFuncionario IUExi = new IUExibeFuncionario(this, true);
        IUExi.setLocationRelativeTo(this);
        IUExi.setVisible(true);
    }//GEN-LAST:event_buscaFunNomeMenuActionPerformed

    private void buscaFuncCodMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaFuncCodMenuActionPerformed
        // TODO add your handling code here:
        IUExibeFuncionario1 IUExi1 = new IUExibeFuncionario1(this, true);
        IUExi1.setLocationRelativeTo(this);
        IUExi1.setVisible(true);
    }//GEN-LAST:event_buscaFuncCodMenuActionPerformed

    private void infoDepMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoDepMenuItemActionPerformed
        // TODO add your handling code here:
        IUInformacoesDep IUInfo = new IUInformacoesDep(this, true);
        IUInfo.setLocationRelativeTo(this);
        IUInfo.setVisible(true);
    }//GEN-LAST:event_infoDepMenuItemActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
         IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
         Controlador control = new Controlador();
        relatorio.exibir("Relatório dos Funcionários", "Funcionários", control.funcionarios());
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório dos Técnicos", "Técnicos", control.tecnicos());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório dos Docentes", "Docentes", control.docentes());
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Docentes Efetivos", "Docentes Efetivos", control.docentesEfetivos());
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatório Docentes Substitutos", "Docentes Substitutos", control.docentesSubstitutos());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void filtrarFunSalarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarFunSalarioMenuItemActionPerformed
        // TODO add your handling code here:
         IURelatorio relatorio = new IURelatorio(this, false);
         Controlador control = new Controlador();
        relatorio.exibir("Funcionário", "Seleção de faixa salarial!");
    }//GEN-LAST:event_filtrarFunSalarioMenuItemActionPerformed

    private void filtrarDepGastosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarDepGastosMenuItemActionPerformed
        // TODO add your handling code here:
        IURelatorio relatorio = new IURelatorio(this, false);
        relatorio.exibir("Departamento", "Seleção de faixa de gastos!");
    }//GEN-LAST:event_filtrarDepGastosMenuItemActionPerformed

    private void resumoDepsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumoDepsMenuItemActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Resumo dos departamentos", "Departamentos", control.resumoDepartamento());
    }//GEN-LAST:event_resumoDepsMenuItemActionPerformed

    private void relatorioGeralMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioGeralMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatorioGeralMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        IURelatorioGenerico relatorio = new IURelatorioGenerico(this, false);
        Controlador control = new Controlador();
        relatorio.exibir("Relatorio geral!", "Departamentos", control.geral());
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IUPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IUPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addEfetivoMenu;
    private javax.swing.JMenuItem addSubMenu;
    private javax.swing.JMenuItem addTecnicoMenu;
    private javax.swing.JMenuItem buscaFunNomeMenu;
    private javax.swing.JMenuItem buscaFuncCodMenu;
    private javax.swing.JMenuItem criaDepartamentoMenu;
    private javax.swing.JMenuItem filtrarDepGastosMenuItem;
    private javax.swing.JMenuItem filtrarFunSalarioMenuItem;
    private javax.swing.JMenuItem infoDepMenuItem;
    private javax.swing.JMenuItem inicializaUniItemMenu;
    private javax.swing.JMenu inicializaUniMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JMenu relatorioGeralMenuItem;
    private javax.swing.JMenuItem resumoDepsMenuItem;
    // End of variables declaration//GEN-END:variables
}
